Traceback (most recent call last):
  File "C:\Users\chenoi\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\chenoi\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (11, 5)  #set default figure size
import numpy as np
from numba import njit, prange, float64, int64
from numba.experimental import jitclass
from interpolation import interp
from math import gamma
from scipy.optimize import minimize
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mSystemError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_38340\1137111295.py[0m in [0;36m<module>[1;34m[0m
[0;32m      3[0m [0mplt[0m[1;33m.[0m[0mrcParams[0m[1;33m[[0m[1;34m"figure.figsize"[0m[1;33m][0m [1;33m=[0m [1;33m([0m[1;36m11[0m[1;33m,[0m [1;36m5[0m[1;33m)[0m  [1;31m#set default figure size[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 5[1;33m [1;32mfrom[0m [0mnumba[0m [1;32mimport[0m [0mnjit[0m[1;33m,[0m [0mprange[0m[1;33m,[0m [0mfloat64[0m[1;33m,[0m [0mint64[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mexperimental[0m [1;32mimport[0m [0mjitclass[0m[1;33m[0m[1;33m[0m[0m
[0;32m      7[0m [1;32mfrom[0m [0minterpolation[0m [1;32mimport[0m [0minterp[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\numba\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m     40[0m [1;33m[0m[0m
[0;32m     41[0m [1;31m# Re-export vectorize decorators and the thread layer querying function[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 42[1;33m from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
[0m[0;32m     43[0m                             get_num_threads, set_num_threads)
[0;32m     44[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\numba\np\ufunc\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# -*- coding: utf-8 -*-[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m[1;33m.[0m[0mdecorators[0m [1;32mimport[0m [0mVectorize[0m[1;33m,[0m [0mGUVectorize[0m[1;33m,[0m [0mvectorize[0m[1;33m,[0m [0mguvectorize[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m[1;33m.[0m[0m_internal[0m [1;32mimport[0m [0mPyUFunc_None[0m[1;33m,[0m [0mPyUFunc_Zero[0m[1;33m,[0m [0mPyUFunc_One[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m [1;32mimport[0m [0m_internal[0m[1;33m,[0m [0marray_exprs[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\numba\np\ufunc\decorators.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mimport[0m [0minspect[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m [1;32mimport[0m [0m_internal[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m[1;33m.[0m[0mparallel[0m [1;32mimport[0m [0mParallelUFuncBuilder[0m[1;33m,[0m [0mParallelGUFuncBuilder[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mSystemError[0m: initialization of _internal failed without raising an exception
SystemError: initialization of _internal failed without raising an exception

